/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1erparcial;

import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleado_estatus = new javax.swing.JComboBox<>();
        empleado_supervisorId = new javax.swing.JTextField();
        empleado_idArea = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        empleado_empresa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        empleado_pago = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        empleado_nss = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empleado_horario = new javax.swing.JTextField();
        empleado_medicamentos = new javax.swing.JTextField();
        empleado_nombre = new javax.swing.JTextField();
        empleado_fechaRegistro = new javax.swing.JTextField();
        empleado_horaRegistro = new javax.swing.JTextField();
        empleado_curp = new javax.swing.JTextField();
        empleado_id = new javax.swing.JTextField();
        empleado_telefono = new javax.swing.JTextField();
        empleado_alergias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_guardarCambios = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empleado_estatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        empleado_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Baja", "Vacaciones", "Incapacidad" }));
        empleado_estatus.setEnabled(false);
        getContentPane().add(empleado_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 140, -1));

        empleado_supervisorId.setEditable(false);
        empleado_supervisorId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empleado_supervisorId.setText("1");
        getContentPane().add(empleado_supervisorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 140, 30));

        empleado_idArea.setEditable(false);
        empleado_idArea.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empleado_idArea.setText("2");
        getContentPane().add(empleado_idArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 140, 30));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ID Area:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, 32));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("SupervisorId");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, 32));

        empleado_empresa.setEditable(false);
        empleado_empresa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empleado_empresa.setText("COORSA");
        getContentPane().add(empleado_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 140, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Horario:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, 52));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pago/Hora:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 94, 30));

        empleado_pago.setEditable(false);
        empleado_pago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empleado_pago.setText("$40.00 MXN");
        getContentPane().add(empleado_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 138, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estatus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, 40));

        empleado_nss.setEditable(false);
        empleado_nss.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_nss.setText("819198383");
        getContentPane().add(empleado_nss, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 140, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NSS:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, 52));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Empresa: ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 32));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 75)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Empleado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        empleado_horario.setEditable(false);
        empleado_horario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        empleado_horario.setText("7:00am - 6:00pm");
        getContentPane().add(empleado_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 137, 30));

        empleado_medicamentos.setEditable(false);
        empleado_medicamentos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_medicamentos.setText("hidrocortisona ");
        getContentPane().add(empleado_medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 220, 30));

        empleado_nombre.setEditable(false);
        empleado_nombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_nombre.setText("Jose Antonio Patiño");
        getContentPane().add(empleado_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 220, 30));

        empleado_fechaRegistro.setEditable(false);
        empleado_fechaRegistro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_fechaRegistro.setText("01/11/2020");
        getContentPane().add(empleado_fechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 220, 30));

        empleado_horaRegistro.setEditable(false);
        empleado_horaRegistro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_horaRegistro.setText("04:30pm");
        getContentPane().add(empleado_horaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 220, 30));

        empleado_curp.setEditable(false);
        empleado_curp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_curp.setText("PAPA001001HQTT");
        getContentPane().add(empleado_curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 220, 30));

        empleado_id.setEditable(false);
        empleado_id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_id.setText("120035990");
        getContentPane().add(empleado_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 220, 30));

        empleado_telefono.setEditable(false);
        empleado_telefono.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_telefono.setText("4428210392");
        getContentPane().add(empleado_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 220, 30));

        empleado_alergias.setEditable(false);
        empleado_alergias.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        empleado_alergias.setText("Abejas");
        getContentPane().add(empleado_alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 220, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Generales Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        btn_guardarCambios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_guardarCambios.setText("Gurdar Cambios");
        btn_guardarCambios.setEnabled(false);
        btn_guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, 170, -1));

        btn_salir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, 80, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos Empresa/Empleado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Medicamento:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, 52));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Alergias:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, 52));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Telefono:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, 52));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Curp:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, 52));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 52));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 200, 180));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Empleado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 52));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora Registro:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 52));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha Registro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 52));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // abrrir el jframe Accesso y cerrar este
        this.dispose();
        new Acceso().setVisible(true);
        
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCambiosActionPerformed
        JOptionPane.showMessageDialog(null, "(simulacion!) Se guardaron los cambios correctamente");
    }//GEN-LAST:event_btn_guardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_guardarCambios;
    public static javax.swing.JButton btn_salir;
    public static javax.swing.JTextField empleado_alergias;
    public static javax.swing.JTextField empleado_curp;
    public static javax.swing.JTextField empleado_empresa;
    public static javax.swing.JComboBox<String> empleado_estatus;
    public static javax.swing.JTextField empleado_fechaRegistro;
    public static javax.swing.JTextField empleado_horaRegistro;
    public static javax.swing.JTextField empleado_horario;
    public static javax.swing.JTextField empleado_id;
    public static javax.swing.JTextField empleado_idArea;
    public static javax.swing.JTextField empleado_medicamentos;
    public static javax.swing.JTextField empleado_nombre;
    public static javax.swing.JTextField empleado_nss;
    public static javax.swing.JTextField empleado_pago;
    public static javax.swing.JTextField empleado_supervisorId;
    public static javax.swing.JTextField empleado_telefono;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
